SSID = "Raccoon City"
SSI_PASSWORD = "crime city"

SERVER_IP = "192.168.1.31"

MAIN_TOPIC = b"LED_MAIN"
SECONDARY_TOPIC = b"LED_SECONDARY"
AMBIENT_TOPIC = b"LED_AMBIENT"

MAIN_PIN_RED = 0
MAIN_PIN_GREEN = 2
MAIN_PIN_BLUE = 4

SECONDARY_PIN_RED = 19
SECONDARY_PIN_GREEN = 21
SECONDARY_PIN_BLUE = 22

AMBIENT_PIN_RED = 5
AMBIENT_PIN_GREEN = 15
AMBIENT_PIN_BLUE = 18
