services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  mqtt-ui:
    image: terdia07/mqttui
    ports:
      - "8787:5000"
    environment:
      - MQTT_BROKER=mqtt
      - MQTT_PORT=1883
